user = User.create!(
  nickname: 'github',
  uid: '12345',
  email: 'github@example.com'
)

Repository.create!(
  user: user,
  owner: 'github',
  name: 'ruby',
  description: 'The Ruby Programming Language',
  homepage_url: 'http://www.ruby-lang.org/',
  total_stars: 151,
  total_watchers: 68,
  total_issues: 0,
  languages: [
    'Ruby',
    'C',
    'Perl',
    'Python',
    'Scheme',
    'Makefile',
    'HTML',
    'Shell',
    'Assembly',
    'C++',
    'CSS',
    'JavaScript',
    'Emacs Lisp',
    'XSLT',
    'Scilab',
    'Yacc',
    'Batchfile',
    'GDB',
    'M4',
    'Ragel',
    'Perl 6',
    'Objective-C',
    'sed',
    'Other',
  ],
  first_commit_at: Time.parse('2013-08-06T01:57:46Z'),
  last_commit_at: Time.parse('2019-08-06T01:57:46Z'),
  last_commits_at: [Time.parse('2013-08-06T01:57:46Z'), Time.parse('2019-08-06T01:57:46Z')],
  licence: 'Other',
  last_synchronized_at: nil,
)
